openapi: 3.2.0
info:
  title: Specific metaproperty operations API
  version: 1.0.0
servers:
- url: https://{your-bynder-domain}/
security:
- OAuth2:
  - METAPROPERTYMANAGEMENT
  - METAMANAGEMENT
- permanentToken:
  - METAPROPERTYMANAGEMENT
  - METAMANAGEMENT
tags:
- name: Specific metaproperty operations
paths:
  /api/v4/metaproperties/{id}:
    get:
      summary: Retrieve specific metaproperty
      tags:
      - Specific metaproperty operations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Metaproperty id.
      - name: count
        in: query
        required: false
        schema:
          type: boolean
          default: false
        description: Indicates whether or not the response should include asset count results for metaproperty-options.
      - name: type
        in: query
        required: false
        schema:
          type: string
          enum:
          - image
          - document
          - audio
          - video
          - 3d
        description: Comma-separated list of asset types. Filters the count results by asset type.
      - name: options
        in: query
        required: false
        schema:
          type: boolean
          default: true
        description: Indicates whether or not the response should include the metaproperty options of the metaproperty.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              examples:
                example-1:
                  value:
                    isMultiselect: false
                    isMultifilter: false
                    isRequired: false
                    isMainfilter: true
                    isFilterable: true
                    isApiField: true
                    isDisplayField: false
                    isDrilldown: false
                    isEditable: true
                    name: colours
                    label: Colours
                    zindex: 16
                    id: 00000000-0000-0000-0000000000000000
                    type: sidebar
                    showInListView: true
                    showInGridView: false
                    showInDuplicateView: false
                    useDependencies: false
                    options:
                    - displayLabel: Yellow
                      date: February, 15 2017 14:54:58 +0000
                      pregeneratedZipFileSize: 0
                      linkedOptionIds: []
                      isSelectable: true
                      zindex: 1
                      product_suffix: ''
                      name: yellow
                      id: 00000000-0000-0000-0000000000000000
                      active: true
                      label: Yellow
                      labels:
                        nl_NL: Geel
                        en_US: Yellow
                      descriptions: {}
                      description: ''
                      hideByDefault: false
                      image: ___URL_TO_BYNDER_CDN___
                    - displayLabel: Red
                      date: February, 15 2017 15:50:55 +0000
                      pregeneratedZipFileSize: 0
                      linkedOptionIds: []
                      isSelectable: true
                      zindex: 1
                      product_suffix: ''
                      name: red
                      id: 00000000-0000-0000-0000000000000000
                      active: true
                      label: Red
                      labels:
                        nl_NL: Rood
                        en_US: Red
                      descriptions: {}
                      description: ''
                      hideByDefault: false
                      image: ___URL_TO_BYNDER_CDN___
        '404':
          description: Metaproperty not found
          content:
            application/json:
              examples:
                example-1:
                  value:
                    message: Metaproperty not found
                    statuscode: 404
    post:
      summary: Modify metaproperty
      description: Requires the METAPROPERTYMANAGEMENT or METAMANAGEMENT security role.
      tags:
      - Specific metaproperty operations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Metaproperty id.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Metaproperty id.
                  example: 00000000-0000-0000-0000000000000000
                data:
                  type: string
                  description: JSON-serialised string
                  example: "{\n  \"type\": \"select\",\n  \"label\": \"Colour\",\n  \"labels\": {\"fr_FR\": \"foo\", \"en_US\": \"foo\"},\n  \"zindex\": 4,\n  \"isEditable\": true,\n  \"isFilterable\": true,\n  \"isMainfilter\": true,\n  \"isMultiselect\": true,\n  \"isRequired\": true,\n  \"isMultifilter\": true,\n  \"isDrilldown\": true,\n  \"isDisplayField\": true,\n  \"isApiField\": true\n}\n"
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example-1:
                  value:
                    message: Created
                    statuscode: 201
        '400':
          description: Invalid metaproperty type
          content:
            application/json:
              examples:
                example-1:
                  value:
                    message: Invalid metaproperty type
                    statuscode: 400
        '404':
          description: Metaproperty not found
          content:
            application/json:
              examples:
                example-1:
                  value:
                    message: Metaproperty not found
                    statuscode: 404
    delete:
      summary: Delete metaproperty
      description: Requires the METAPROPERTYMANAGEMENT or METAMANAGEMENT security role.
      tags:
      - Specific metaproperty operations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Metaproperty id.
      responses:
        '204':
          description: No Content
        '404':
          description: Metaproperty not found
          content:
            application/json:
              examples:
                example-1:
                  value:
                    message: Metaproperty not found
                    statuscode: 404
components:
  securitySchemes:
    permanentToken:
      type: apiKey
      in: header
      name: Authorization
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            METAPROPERTYMANAGEMENT: ''
            METAMANAGEMENT: ''
        authorizationCode:
          authorizationUrl: https://{your-auth-url}
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            METAPROPERTYMANAGEMENT: ''
            METAMANAGEMENT: ''
